#!/usr/bin/env python3
"""Compare Flask routes in web/server.py against FastAPI routes in web/server_fastapi.py."""

from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FLASK_FILE = ROOT / "web" / "server.py"
FASTAPI_FILE = ROOT / "web" / "server_fastapi.py"
OUT_FILE = ROOT / "docs" / "flask-migration-status.md"


def parse_flask_routes(text: str) -> set[tuple[str, str]]:
    routes: set[tuple[str, str]] = set()
    pattern = re.compile(r"@app\.route\(\s*['\"]([^'\"]+)['\"](?:,\s*methods\s*=\s*\[([^\]]+)\])?", re.MULTILINE)
    for match in pattern.finditer(text):
        path = match.group(1)
        methods_part = match.group(2)
        if methods_part:
            methods = re.findall(r"['\"]([A-Z]+)['\"]", methods_part)
        else:
            methods = ["GET"]
        for method in methods:
            routes.add((method, path))
    return routes


def parse_fastapi_routes(text: str) -> set[tuple[str, str]]:
    routes: set[tuple[str, str]] = set()
    pattern = re.compile(r"@app\.(get|post|put|delete|patch)\(\s*['\"]([^'\"]+)['\"]")
    for method, path in pattern.findall(text):
        routes.add((method.upper(), path))
    return routes


def format_routes(routes: list[tuple[str, str]]) -> str:
    if not routes:
        return "- _(none)_\n"
    return "".join(f"- `{method} {path}`\n" for method, path in routes)


def main() -> None:
    flask_routes = parse_flask_routes(FLASK_FILE.read_text())
    fastapi_routes = parse_fastapi_routes(FASTAPI_FILE.read_text())

    missing_in_fastapi = sorted(flask_routes - fastapi_routes)
    shared = sorted(flask_routes & fastapi_routes)
    fastapi_only = sorted(fastapi_routes - flask_routes)

    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(
        "\n".join(
            [
                "# Flask → FastAPI Migration Status",
                "",
                "_Auto-generated by `tools/route_audit.py`._",
                "",
                f"- Flask routes discovered: **{len(flask_routes)}**",
                f"- FastAPI routes discovered: **{len(fastapi_routes)}**",
                f"- Shared route signatures: **{len(shared)}**",
                f"- Flask signatures missing in FastAPI: **{len(missing_in_fastapi)}**",
                f"- FastAPI-only signatures: **{len(fastapi_only)}**",
                "",
                "## Shared routes",
                format_routes(shared),
                "## Missing in FastAPI (from Flask)",
                format_routes(missing_in_fastapi),
                "## FastAPI-only routes",
                format_routes(fastapi_only),
            ]
        )
    )


if __name__ == "__main__":
    main()
