#!/usr/bin/env python3
"""Audit script has completed the migration. No Flask routes left."""

import os
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FASTAPI_FILE = ROOT / "web" / "server_fastapi.py"
OUT_FILE = ROOT / "docs" / "flask-migration-status.md"

def main() -> None:
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(
        "\n".join(
            [
                "# Flask → FastAPI Migration Status",
                "",
                "_Auto-generated by `tools/route_audit.py`._",
                "",
                "The migration is complete. The Flask server has been removed.",
                "",
                "All routes are now in FastAPI.",
            ]
        )
    )

if __name__ == "__main__":
    main()
